# user
server.port=${PORT:8080}
spring.config.import=optional:file:./application-local.properties
spring.application.name=user-service
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/ecommerce}
spring.data.mongodb.database=ecommerce
jwt.secret=${JWT_SECRET}
frontend.url=${FRONTEND_URL:http://localhost:5173}