package com.shopwebsite.cart;
import org.springframework.web.server.ResponseStatusException;
import jakarta.validation.constraints.Min;import org.springframework.beans.factory.annotation.Value;import org.springframework.http.*;import org.springframework.web.bind.annotation.*;import org.springframework.web.client.RestTemplate;import java.util.*;
@RestController @RequestMapping("/api/carts") public class CartController { private final CartRepository repo;private final RestTemplate http;private final String products; public CartController(CartRepository repo,RestTemplate http,@Value("${product.service.url}")String products){this.repo=repo;this.http=http;this.products=products;}
 @GetMapping("/{userId}") public Cart get(@PathVariable String userId){return repo.findById(userId).orElseGet(()->repo.save(new Cart(userId)));}
 @PostMapping("/{userId}/items") public Cart add(@PathVariable String userId,@RequestBody ItemRequest request){Product p=http.getForObject(products+"/api/products/"+request.productId(),Product.class);if(p==null)throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Product not found");if(request.quantity()>p.stock())throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Only "+p.stock()+" item(s) left in stock");Cart c=get(userId);c.getItems().removeIf(i->i.productId().equals(request.productId()));c.getItems().add(new Cart.Item(p.id(),p.name(),p.price(),request.quantity(),p.emoji()));return repo.save(c);}
 @PutMapping("/{userId}/items/{productId}") public Cart update(@PathVariable String userId,@PathVariable String productId,@RequestBody Quantity q){Product p=http.getForObject(products+"/api/products/"+productId,Product.class);if(p==null)throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Product not found");if(q.quantity()>p.stock())throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Only "+p.stock()+" item(s) left in stock");Cart c=get(userId);replace(c,productId,q.quantity());return repo.save(c);}
 @DeleteMapping("/{userId}/items/{productId}") public Cart remove(@PathVariable String userId,@PathVariable String productId){Cart c=get(userId);c.getItems().removeIf(i->i.productId().equals(productId));return repo.save(c);}
 private void replace(Cart c,String id,int q){if(q<1)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Quantity must be positive");List<Cart.Item> x=c.getItems();for(int i=0;i<x.size();i++)if(x.get(i).productId().equals(id)){Cart.Item old=x.get(i);x.set(i,new Cart.Item(old.productId(),old.productName(),old.price(),q,old.emoji()));return;}}
 public record ItemRequest(String productId,@Min(1)int quantity){} public record Quantity(@Min(1)int quantity){} public record Product(String id,String name,java.math.BigDecimal price,int stock,String description,String emoji){}
}
