server.port=8083
spring.application.name=order-service
spring.data.mongodb.uri=mongodb://localhost:27017/ecommerce
spring.data.mongodb.database=ecommerce
user.service.url=http://localhost:8080
product.service.url=http://localhost:8081
