package com.shopwebsite.order;
import org.springframework.web.server.ResponseStatusException;
import jakarta.validation.Valid;import jakarta.validation.constraints.NotBlank;import org.springframework.beans.factory.annotation.Value;import org.springframework.http.*;import org.springframework.web.bind.annotation.*;import org.springframework.web.client.HttpStatusCodeException;import org.springframework.web.client.RestTemplate;import java.math.BigDecimal;import java.time.Instant;import java.util.*;
@RestController @RequestMapping("/api/orders") public class OrderController {private final OrderRepository repo;private final RestTemplate http;private final String users;private final String products;public OrderController(OrderRepository repo,RestTemplate http,@Value("${user.service.url}")String users,@Value("${product.service.url}")String products){this.repo=repo;this.http=http;this.users=users;this.products=products;}
 @PostMapping @ResponseStatus(HttpStatus.CREATED) public Order create(@Valid @RequestBody Checkout req){try{http.getForObject(users+"/api/users/"+req.userId(),Object.class);}catch(Exception e){throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"User does not exist",e);}if(req.items()==null||req.items().isEmpty())throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Cart is empty");for(Order.Item item:req.items()){try{http.postForObject(products+"/api/products/"+item.productId()+"/reserve?quantity="+item.quantity(),null,Object.class);}catch(HttpStatusCodeException e){throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Product service rejected "+item.productName()+": "+e.getResponseBodyAsString(),e);}catch(Exception e){throw new ResponseStatusException(HttpStatus.SERVICE_UNAVAILABLE,"Product service is unavailable while reserving "+item.productName(),e);}}Order o=new Order();o.setUserId(req.userId());o.setAddress(req.address());o.setPaymentMethod(req.paymentMethod());o.setItems(req.items());o.setTotal(req.items().stream().map(i->i.price().multiply(BigDecimal.valueOf(i.quantity()))).reduce(BigDecimal.ZERO,BigDecimal::add));o.setStatus("PLACED");o.setCreatedAt(Instant.now());return repo.save(o);}
 @GetMapping("/user/{userId}") public List<Order> mine(@PathVariable String userId){return repo.findByUserIdOrderByCreatedAtDesc(userId);}
 @GetMapping public List<Order> all(@RequestHeader("X-Role")String role){admin(role);return repo.findAll();}
 @PatchMapping("/{id}/status") public Order status(@RequestHeader("X-Role")String role,@PathVariable String id,@RequestBody Status s){admin(role);Order o=repo.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Order not found"));o.setStatus(s.status());return repo.save(o);}
 private void admin(String role){if(!"ADMIN".equals(role))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Admin role required");}
 public record Checkout(@NotBlank String userId,@NotBlank String address,@NotBlank String paymentMethod,List<Order.Item> items){}public record Status(@NotBlank String status){}
}
