<template>
  <section class="dashboard">
    <div class="page-heading"><div><h1>Admin dashboard</h1><p>Quick view of catalog and order activity.</p></div><router-link class="back-link" to="/products">Manage products</router-link></div>
    <div v-if="loading" class="status">Loading dashboard...</div><p v-else-if="error" class="status error">{{ error }}</p>
    <template v-else>
      <div class="metric-grid"><div class="metric"><span>Total products</span><strong>{{ products.length }}</strong></div><div class="metric"><span>Inventory units</span><strong>{{ inventoryUnits }}</strong></div><div class="metric"><span>Total orders</span><strong>{{ orders.length }}</strong></div><div class="metric"><span>Order revenue</span><strong>Rs.{{ revenue.toFixed(2) }}</strong></div></div>
      <div class="dashboard-grid"><section class="dashboard-card"><h2>Needs attention</h2><p v-if="!lowStock.length" class="muted">All products have healthy stock.</p><ul v-else><li v-for="product in lowStock" :key="product.id"><span>{{ product.name }}</span><b>{{ product.stock }} left</b></li></ul><p class="pending"><strong>{{ pendingOrders }}</strong> orders are still in progress.</p></section><section class="dashboard-card"><h2>Recent orders</h2><p v-if="!orders.length" class="muted">No orders yet.</p><ul v-else><li v-for="order in recentOrders" :key="order.id"><span>#{{ order.id.slice(0, 8) }}</span><b>{{ order.status }} · Rs.{{ order.total }}</b></li></ul></section></div>
    </template>
  </section>
</template>
<script>
import axios from 'axios'
export default { data: () => ({ products: [], orders: [], loading: true, error: null }), computed: { inventoryUnits() { return this.products.reduce((sum, p) => sum + Number(p.stock || 0), 0) }, lowStock() { return this.products.filter(p => Number(p.stock) <= 5) }, revenue() { return this.orders.reduce((sum, o) => sum + Number(o.total || 0), 0) }, pendingOrders() { return this.orders.filter(o => !['DELIVERED', 'CANCELLED'].includes(o.status)).length }, recentOrders() { return this.orders.slice().sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt)).slice(0, 5) } }, async created() { try { const [products, orders] = await Promise.all([axios.get('/api/products'), axios.get('/api/orders')]); this.products = products.data; this.orders = orders.data } catch (e) { this.error = 'Unable to load dashboard data.' } finally { this.loading = false } } }
</script>
<style scoped>
.dashboard{max-width:1100px;margin:0 auto}.page-heading{display:flex;justify-content:space-between;align-items:center;margin-bottom:24px}.page-heading h1{margin-bottom:6px}.page-heading p,.muted{color:#666}.back-link{background:#4a00e0;color:white;padding:10px 14px;border-radius:4px;text-decoration:none}.metric-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin-bottom:22px}.metric,.dashboard-card{background:white;border:1px solid #ddd;border-radius:6px;padding:18px}.metric{display:grid;gap:10px}.metric span{color:#666;font-size:.9rem}.metric strong{color:#4a00e0;font-size:1.45rem}.dashboard-grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}.dashboard-card h2{font-size:1.1rem;margin-bottom:15px}.dashboard-card ul{list-style:none}.dashboard-card li{display:flex;justify-content:space-between;gap:15px;padding:11px 0;border-bottom:1px solid #eee}.dashboard-card li:last-child{border-bottom:0}.dashboard-card li b{color:#4a00e0;font-size:.9rem}.pending{margin-top:18px;color:#c0392b}.status{text-align:center;padding:32px;color:#555}.error{color:#c0392b}@media (max-width:750px){.metric-grid,.dashboard-grid{grid-template-columns:1fr 1fr}.page-heading{align-items:flex-start;gap:15px;flex-direction:column}}
</style>
